
import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">

      <Head>
        <meta name="twitter:title" content="test title" />
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"/>
      </Head>
    
      <body className={inter.className} >
        {children}
      </body>
    
    </html>
  )
}
